// The composition root supplies modules; origin does not grant extra services.
const module = (
  id,
  name,
  description,
  surfaces,
  entry,
  requires,
  navigation,
  required = false,
) => ({
  id,
  builtin: true,
  required,
  enabled: true,
  manifest: {
    apiVersion: 1,
    id,
    name,
    description,
    surfaces,
    entry: new URL(entry, import.meta.url).href,
    requires,
    ...(navigation ? { navigation } : {}),
  },
});
export const builtins = [
  module(
    "appearance",
    "Внешний вид",
    "Размер текста, ширина диалога и анимации.",
    ["settings"],
    "./appearance.js",
    ["client.preferences"],
    { group: "settings", icon: "settings" },
  ),
  module(
    "chat",
    "Чат",
    "Отправка сообщений, инструменты и автопрокрутка.",
    ["settings"],
    "./chat.js",
    ["client.preferences"],
    { group: "settings", icon: "chat" },
  ),
  module(
    "shortcuts",
    "Сочетания клавиш",
    "Настройка команд клавиатуры.",
    ["settings"],
    "./shortcuts.js",
    [],
    { group: "settings", icon: "keyboard" },
  ),
  module(
    "extensions",
    "Расширения",
    "Установка, включение и выбор расширений интерфейса.",
    ["settings"],
    "./manager.js",
    ["client.modules"],
    { group: "settings", icon: "modules" },
    true,
  ),
  module(
    "diagnostic-usage",
    "Расход и контекст",
    "Расход токенов, запросы и снимок контекста.",
    ["settings"],
    "./usage.js",
    ["client.diagnostics"],
    { group: "diagnostics", icon: "analysis" },
  ),
  module(
    "diagnostic-analysis",
    "Анализ ходов",
    "Ходы агента, инструменты, ошибки и сообщения.",
    ["settings"],
    "./analysis.js",
    ["client.diagnostics"],
    { group: "diagnostics", icon: "inspector" },
  ),
  module(
    "diagnostic-configs",
    "Сборка агента",
    "Профиль, модули агента и их конфигурация.",
    ["settings"],
    "./configs.js",
    ["client.diagnostics"],
    { group: "diagnostics", icon: "modules" },
  ),
  module(
    "diagnostic-architecture",
    "Архитектура",
    "Связи модулей и конфигурация runtime.",
    ["settings"],
    "./architecture.js",
    ["client.diagnostics"],
    { group: "diagnostics", icon: "inspector" },
  ),
  module(
    "model-selector",
    "Модель и рассуждение",
    "Выбор модели и уровня рассуждения. Отключать не рекомендуется.",
    ["composer-model"],
    "./model.js",
    ["client.composer"],
  ),
  module(
    "access-selector",
    "Режим доступа",
    "Выбор режима доступа агента. Отключение селектора не меняет действующий режим.",
    ["composer-access"],
    "./access.js",
    ["client.composer"],
  ),
];
