// The composition root supplies modules; origin does not grant extra services.
const module = (
  id,
  name,
  description,
  surfaces,
  entry,
  requires,
  icon,
  required = false,
  settingsGroup = "builtin",
  layout = "form",
) => ({
  id,
  source: "builtin",
  settingsGroup,
  required,
  enabled: true,
  manifest: {
    apiVersion: 2,
    id,
    name,
    description,
    ...(icon ? { icon } : {}),
    ...(settingsGroup === 'builtin' ? { preview: { src: '../../extensions/previews/' + id + '.svg', alt: 'Пример интерфейса: ' + name } } : {}),
    views: [{ surfaces, entry: new URL(entry, import.meta.url).href, requires, layout, isolation: "light" }],
  },
});
// Agent settings edit the saved profile through the public config builder API.
const agentPage = (id, name, description, entry, icon) =>
  module(
    id,
    name,
    description,
    ["settings"],
    entry,
    ["agent.config.builder"],
    icon,
    true,
    "agent",
    "editor",
  );
export const builtins = [
  agentPage("agent-model", "Модель", "Модель профиля и параметры её модуля.", "./agent/model.js", "model"),
  agentPage("agent-workflow", "Рабочий цикл", "Алгоритм шагов агента.", "./agent/slot.js?slot=workflow", "workflow"),
  agentPage("agent-context", "Контекст", "Сведения, которые получает модель.", "./agent/slot.js?slot=context", "layers"),
  agentPage("agent-compactor", "Сжатие истории", "Сокращение длинной истории.", "./agent/slot.js?slot=compactor", "compress"),
  agentPage("agent-tools", "Инструменты", "Разрешённые инструменты и их отбор для модели.", "./agent/tools.js", "wrench"),
  agentPage("agent-access", "Права и подтверждения", "Режим прав и политика подтверждений.", "./agent/access.js", "shield"),
  agentPage("agent-patch", "Правки файлов", "Применение изменений к файлам.", "./agent/slot.js?slot=patch", "patch"),
  agentPage("agent-search", "Поиск", "Поиск по рабочему проекту.", "./agent/slot.js?slot=search", "search"),
  agentPage("agent-memory", "Память", "Сведения между обращениями.", "./agent/slot.js?slot=memory", "database"),
  agentPage("agent-hooks", "Обработчики", "Порядок и параметры hooks.", "./agent/hooks.js", "link"),
  agentPage("agent-history", "История изменений", "Заменённые состояния профиля и откат.", "./agent/history.js", "history"),
  module(
    "appearance",
    "Внешний вид",
    "Размер текста, ширина диалога и анимации.",
    ["settings"],
    "./appearance.js",
    ["client.preferences"],
    "settings",
  ),
  module(
    "chat",
    "Чат",
    "Отправка сообщений, инструменты и автопрокрутка.",
    ["settings"],
    "./chat.js",
    ["client.preferences"],
    "chat",
  ),
  module(
    "shortcuts",
    "Сочетания клавиш",
    "Настройка команд клавиатуры.",
    ["settings"],
    "./shortcuts.js",
    [],
    "keyboard",
  ),
  module(
    "extensions",
    "Расширения",
    "Установка, включение и выбор расширений интерфейса.",
    ["settings"],
    "./manager.js",
    ["client.modules"],
    "modules",
    true,
  ),
  module(
    "model-selector",
    "Модель и рассуждение",
    "Выбор модели и уровня рассуждения. Отключать не рекомендуется.",
    ["composer-model"],
    "./model.js",
    ["client.composer"],
  ),
  module(
    "access-selector",
    "Режим доступа",
    "Выбор режима доступа агента. Отключение селектора не меняет действующий режим.",
    ["composer-access"],
    "./access.js",
    ["client.composer"],
  ),
];
